language: node_js
node_js:
  - '8'
dist: trusty
services:
  - mongodb
  - redis-server
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
afterscript:
  - npm run build
