language: node_js
node_js:
  - '12'
matrix:
  include:
    - sudo: required
    - os: osx
      osx_image: xcode7.2
dist: trusty
sudo: required
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
# install:
#   - npm install
# beforescript:
script:
  - npm install
  - nohup npm run start &
  # - sleep 3
  - npm run build
  - npm run test
