language: node_js
node_js:
  - '10'
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
install: travis_wait 20 mvn install
cache:
  directories:
    - node_modules
    - client/node_modules
# install:
#   - npm install
# beforescript:
script:
  - npm install
  - nohup npm run start &
  # - sleep 3
  - npm run build
  - npm run test
